[feature/WEEK 2] Part 1 커밋
SOPTAndroidAdvancedStudy/Blog pull request #9
Opened 2021-09-17 06:02 UTC by sery270

- [x] 메인 스레드와 Handler part 1 - Handler와 Looper 그리고 MessageQueue의 동작 방식 
- [ ] 메인 스레드와 Handler Part 2 -  안드로이드 애플리케이션에서의 메인 스레드

- WEEK 3의 내용인 2.5장(invalidate())은 생략하였습니다.
- 아래와 같은 이유로 2.6장(ANR)을 생략하고 초고를 작성하였습니다. 
  - WEEK2에서 전달하고자 하는 내용이 너무 광범위해져 아티클의 방향이 모호해진다고 판단하였습니다.  
  - ANR에 대해선 간단히 언급하는 것이 아니라 WEEK를 투자하여 다뤄도 좋을만한 주제라 생각하였습니다.

2021-09-17 15:46 UTC, kym1924 approved these changes

2021-09-18 12:33 UTC, l2hyunwoo reviewed
우선 Approve보단 너의 생각을 한번 들어보고자 Comment만 달아놓음

2021-09-18 12:33 UTC, l2hyunwoo commented on Week2/SIBA WEEK 2 Part 1.md
> +그렇다면 과연 *pop한 내용물이 null일때* , 즉 if (msg == null) 가 언제 참이 될까요 ? 바로 Looper를 종료하는 메서드인 quit(), quitSafely()가 호출될 때 입니다. 두 메서드는 결국 MesseageQueue의 quit()를 호출하며, 이의 결과로 queue.next()에서 null 반환되어 위의 if문을 통과하게
```suggestion
그렇다면 과연 *pop한 내용물이 null일때* , 즉 if (msg == null) 가 언제 참이 될까요 ? 

바로 Looper를 종료하는 메서드인 **quit(), quitSafely()**가 호출될 때 입니다. 두 메서드는 결국 MesseageQueue의 quit()를 호출하며, 이의 결과로 queue.next()에서 null 반환되어 위의 if문을 통과하게 되는 것입니다. 이로써 Looper가 종료됩니다. 
```

강조하는 부분은 문단을 분리해줘서 가독성을 높여주는 것도 좋을 것 같아용

+) quit, quitSafely 함수가 Looper를 종료하는 메서드인 점을 설명해주는 것은 베리베리 ~뮤우뮤우~ 굿, 이 함수 내부 기작도 좀 살펴보거나 코드를 발췌하고 주석을 좀 적어주면 더 좋을 것 같음(내 취향)

2021-09-18 12:33 UTC, l2hyunwoo commented on Week2/SIBA WEEK 2 Part 1.md
> +Message를 생성할 때는 사용한 Message 객체를 다시 초기화하여 재사용하는 방식인 오프젝트 풀 방식을 사용합니다. 따라서 **Message 객체는 Message.obtain() 이나 Handler.obtainMessage()을 통해 얻고 관리되어야합니다**.
추가적인 아티클로 Singleton 패턴과 Object 풀 패턴 관련해서 글 적어봐도 좋을 것 같네요. 이건 나중에 따로 적어보도록 하겠습니다.

2021-09-18 12:33 UTC, l2hyunwoo commented on Week2/SIBA WEEK 2 Part 1.md
> +MessageQueue에 Message가 enqueue되는 알고리즘에는 타임스탬프(when + delay) 라는 변수 영향을 줍니다. Message를 enqueue하는 데에는 when이라는 값 이외에 개발자가 delay라는 값을 설정할 수 있습니다. 즉 타임스탬프 값에 따라, MessageQueue의 중간에 enqueue해야하는 경우가 발생하게 빈번히 발
정보가 한 문단에 쏠려있어서 읽기가 살짝 버겁습니다. 모바일, 온라인 환경에서 이를 읽는다 했을 때 각 문장별로 문단 분리를 했을 때 이해 증진에 도움이 될 것 같습니다.
```suggestion
MessageQueue에 Message가 enqueue되는 알고리즘에는 타임스탬프(when + delay) 라는 변수 영향을 줍니다. Message를 enqueue하는 데에는 when이라는 값 이외에 개발자가 delay라는 값을 설정할 수 있습니다. 

즉 타임스탬프 값에 따라, MessageQueue의 중간에 enqueue해야하는 경우가 발생하게 빈번히 발생하게 됩니다. 중간 삽입에 편리한 구조를 사용한다는점에서, 배열 구조가 아닌 링크 구조로 구현되어있다고 이해할 수 있습니다. 

또한, 링크 구조는 일반적으로 요소의 개수 제한이 없어 수많은 Message를 담아야하는 MessageQueue에게 적합하다고 볼 수 있습니다. 따라서, MessageQueue는 위의 이유들로 인해 LinkedQueue로 구현되어있습니다.
```

2021-09-18 12:33 UTC, l2hyunwoo commented on Week2/SIBA WEEK 2 Part 1.md
> +또한 Message의 처리 시점에 따라 -Delayed(), -AtTime(), -AtFrontOfQueue 방식으로 나뉘게 됩니다.
```suggestion
또한 Message의 처리 시점에 따라 아래와 같은 함수들을 호출할 수 있습니다.

- ~Delayed()
- ~AtTime()
- ~AtFrontOfQueue()
```

2021-09-21 14:06 UTC, jinsu4755 reviewed
리뷰가 늦어서 죄송합니다!
내용이 알차게 잘 들어있는 것 같아서 넘모 멋지다

리뷰로 겹칠 내용 빼고 공백문자 하나랑 작성방식에 대한 리뷰하나 남겨두었으니 확인해줘~

2021-09-28 05:18 UTC, sery270 commented on Week2/SIBA WEEK 2 Part 1.md
> +MessageQueue에 Message가 enqueue되는 알고리즘에는 타임스탬프(when + delay) 라는 변수 영향을 줍니다. Message를 enqueue하는 데에는 when이라는 값 이외에 개발자가 delay라는 값을 설정할 수 있습니다. 즉 타임스탬프 값에 따라, MessageQueue의 중간에 enqueue해야하는 경우가 발생하게 빈번히 발
생각지 못한 부분이에요 바로 반영해둘게요

2021-09-28 05:22 UTC, sery270 commented on Week2/SIBA WEEK 2 Part 1.md
> +**일반스레드**의 Looper를 생성하는 방법은 **prepare() 함수를 사용**하는 것 입니다. 또한 메인스레드와 마찬가지로, loop() 호출을 통해 동작하게 됩니다. 정리하면, 개발자는 일반스레드를 사용하는 곳에서 **prepare() 호출**을 통해 **Looper**를 **생성**하고 **loop() 호출**에 의해 **Looper**를 *
이것도 생각지 못했는데, 다시 읽어보니까 집중하기힘드네요 ! 반영하겠습니다

2021-09-28 16:53 UTC, l2hyunwoo approved these changes
추가적으로 작성한 내용이 좋습니다 굳굳

2021-09-29 02:46 UTC, kym1924 commented on Week2/SIBA WEEK 2 Part 1.md
> +그렇다면 Looper는 어떻게 생성되고 관리될까요? 일단 기본적으로 Looper는 각 스레드에 종속되며, MesseageQueue는 각 Looper에 종속됩니다.
진수눈썰미좋았습니다

2021-09-29 03:04 UTC, kym1924 requested changes

2021-09-29 03:04 UTC, kym1924 commented on Week2/SIBA WEEK 2 Part 2.md
> +메인 스레드와 Handler Part2 -  안드로이드 애플리케이션에서의 메인 스레드
```suggestion
메인 스레드와 Handler Part2 - 안드로이드 애플리케이션에서의 메인 스레드
```
공백이 두 번 찍혔네요

2021-09-29 03:04 UTC, kym1924 commented on Week2/SIBA WEEK 2 Part 2.md
> +- 안드로이드 애플리케이션에서  Handler와 Looper 그리고 MessageQueue 구조가 어떻게 쓰이는지 알아봅니다.
```suggestion
- 안드로이드 애플리케이션에서 Handler와 Looper 그리고 MessageQueue 구조가 어떻게 쓰이는지 알아봅니다.
```
공백이 두 번 찍혔네요

2021-09-29 03:04 UTC, kym1924 commented on Week2/SIBA WEEK 2 Part 2.md
> +앞서 Part 1에서 알아보았던,  Handler와 Looper 그리고 MessageQueue의 동작이 과연 왜 필요할까요 ? 바로 여러 스레드를 사용하는 멀티스레드 환경에서, 특정 스레드에게 일을 위임하기 위한 수단으로 의미가 있습니다.
```suggestion
앞서 Part 1에서 알아보았던, Handler와 Looper 그리고 MessageQueue의 동작이 과연 왜 필요할까요? 바로 여러 스레드를 사용하는 멀티스레드 환경에서, 특정 스레드에게 일을 위임하기 위한 수단으로 의미가 있습니다.
```
공백이 두 번 찍혔네요

2021-10-01 04:42 UTC, kym1924 approved these changes

2021-10-10 06:56 UTC, merged